### PR TITLE
JS: synchronous JS method is implemented to JSWriteTo

### PR DESCRIPTION
**Pull request by ttttmr**
go test passed

Reference https://github.com/tdewolff/parse/commit/ab2fa7073eee7b722b44a1d2bf3c8c30cd5d4731

### CODE REVIEW

**Comment by tdewolff** [comment]
Why don't we return an `int` instead of an `int64`? That would clean up the code a bit and puts it in-line with the `io.Writer` interface. The difference can only be felt after 4GB on a 32-bit system, both of which are unlikely...

**Comment by ttttmr** [comment]
At first, I planned to implement [`io.WriterTo`](https://pkg.go.dev/io#WriterTo), so it is int64. The name of the WriterTo method is easy to confuse writing JS or String, so I named it JSWriteTo , continue to use int64

**Comment by ttttmr** [comment]
There seems to be no difference between int and int64 here, I will change them to use int later

**Comment by tdewolff** [comment]
Ah I see, that isn't very nice of Go to have the int/int64 discrepancy. Thanks for the PR!!

**Pull request merged**
