### PR TITLE
Remove redundant conditionals in ShiftBuffer.Err

### PR DESCRIPTION
**Pull request by ciarand**

### CODE REVIEW

**Comment by tdewolff** [comment]
The refactor does not equal the output of the original code. Namely, if `readerr == EOF` but it has not encountered the end of the internal buffer (`z.pos+z.n < len(z.buf)`) it should return `nil`. It could be somewhat refactored though, I agree.

**Comment by ciarand** [comment]
Oh that's embarrassing, that's what I get for looking at code late at night.

**Comment by tdewolff** [comment]
This rewrite looks better none-the-less: 615238da09f51d68dede4bf198f82a855d1b64b9

**Comment by ciarand** [comment]
:+1: nice

**Pull request closed without merging**
